// Decompiled with JetBrains decompiler
// Type: ObjectLayer
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: A8D8CAFB-CD16-4CDA-9F47-7D36796BFC75
// Assembly location: H:\Steam\steamapps\common\OxygenNotIncluded\OxygenNotIncluded_Data\Managed\Assembly-CSharp.dll

public enum ObjectLayer
{
  Minion,
  Building,
  Backwall,
  Pickupables,
  Canvases,
  Plants,
  FillPlacer,
  DigPlacer,
  MopPlacer,
  FoundationTile,
  PlasticTile,
  ReplacementTile,
  GasConduit,
  GasConduitTile,
  ReplacementGasConduit,
  GasConduitConnection,
  LiquidConduit,
  LiquidConduitTile,
  ReplacementLiquidConduit,
  LiquidConduitConnection,
  SolidConduit,
  SolidConduitTile,
  ReplacementSolidConduit,
  SolidConduitConnection,
  LadderTile,
  ReplacementLadder,
  Wire,
  WireTile,
  ReplacementWire,
  WireConnectors,
  LogicGate,
  LogicWire,
  LogicWireTile,
  ReplacementLogicWire,
  TravelTube,
  TravelTubeTile,
  ReplacementTravelTube,
  TravelTubeConnection,
  AttachableBuilding,
  Gantry,
  NumLayers,
}
